stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker rm cont || true
    - docker build -t tetrisant .
    - docker run --name cont tetrisant
    - ls -la
    - docker cp cont:/app/bin/Tetris.jar Tetris.jar
    - docker stop cont
    - docker rm cont
  artifacts:
    paths:
      - Tetris.jar
  tags:
    - dosi

deploy:
  stage: deploy
  script:
    - echo "Logging into Docker Hub...."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Tagging and pushing image to Docker Hub..."
    - docker tag tetrisant sciencefear/tetrisant:$CI_COMMIT_TAG
    - echo "Pushing image to Docker Hub..."
    - docker push sciencefear/tetrisant:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)$/ && $CI_COMMIT_BRANCH == "master"'
      when: manual
  tags:
    - dosi