stages:
  - build
  - notify

variables:
    DOCKER_DRIVER: overlay2 

build:
  stage: build
  image: docker:latest
  services:
     - docker:dind
  script:
    - docker build -t TetrisAnt:latest .
  artifacts:
    paths:
      - bin/Tetris.jar
  tags:
    - dosi
