stages:
  - build

build:
  stage: build
  script:
    - docker stop conteneur
    - docker rm conteneur
    - docker build -t tetrisant .
    - docker run -d --name conteneur tetrisant
    - docker exec test_container ls -la /app/bin
    - docker cp conteneur:/app/bin/Tetris.jar Tetris.jar

  artifacts:
    paths:
      - Tetris.jar
  tags:
    - dosi

