stages:
  - build

build:
  stage: build
  script:
    - mkdir -p bin  # Créez le dossier bin s'il n'existe pas
    - docker build -t tetrisant .
    - |
      if [ $(docker ps -aq -f name=conteneur) ]; then
        docker stop conteneur
        docker rm conteneur
      fi
    - docker run -d --name conteneur tetrisant
    - docker cp conteneur:/app/bin/Tetris.jar bin/Tetris.jar
    - docker stop conteneur  # Arrêtez le conteneur après avoir copié le fichier
    - docker rm conteneur  # Supprimez le conteneur après utilisation

  artifacts:
    paths:
      - bin/Tetris.jar
  tags:
    - dosi
