stages:
  - build

variables:
    DOCKER_DRIVER: overlay2 
    

build:
  stage: build
  script:
    - docker build -t TetrisAnt:latest .
  artifacts:
    paths:
      - bin/Tetris.jar
  tags:
    - dosi
