stages:
  - build

build:
  stage: build
  script:
    - docker build -t tetrisant .
    - docker run -d --name conteneur testrisant
    - docker cp conteneur:/app/bin/Tetris.jar bin/Tetris.jar

  artifacts:
    paths:
      - bin/Tetris.jar
  tags:
    - dosi

