stages:
  - build

build:
  stage: build
  script:
    - docker rm cont || true
    - docker build -t tetrisant .
    - docker run -d --name cont tetrisant
    - ls -la
    - docker cp cont:/app/bin/Tetris.jar Tetris.jar
    - docker stop cont
    - docker rm cont
  artifacts:
    paths:
      - Tetris.jar
  tags:
    - dosi

