stages:
  - build

build:
  stage: build
  script:
    - docker build -t tetrisant:latest .
    - docker run -d --name cont testristant
    - docker cp cont:/app/dist/Tetris.jar Tetris.jar
    - docker stop cont
    - docker rm cont
  artifacts:
    paths:
      - Tetris.jar
  tags:
    - dosi
